{dkrajzew} merging with trunk
git-svn-id: http://svn.code.sf.net/p/sumo/code/branches/dkrajzew@15039 29f149b2-0c63-11e1-8f5c-a347f6a9acd0

diff --git a/tools/build/dailyUpdateMakeGCC b/tools/build/dailyUpdateMakeGCC
--- a/tools/build/dailyUpdateMakeGCC
+++ b/tools/build/dailyUpdateMakeGCC
@@ -45,8 +45,7 @@ if make >> $MAKELOG 2>&1; then
             scp -q $f $REMOTEDIR
           fi
         done
-        rsync -r $PREFIX/sumo/docs/wiki/docs $REMOTEDIR
-        rsync -r $PREFIX/sumo/docs/pydoc $PREFIX/sumo/docs/doxygen $REMOTEDIR/docs
+        rsync -rcz $PREFIX/sumo/docs/pydoc $PREFIX/sumo/docs/doxygen $PREFIX/sumo/docs/userdoc $REMOTEDIR
       else
         echo "make dist-complete failed" | tee -a $STATUSLOG; tail -10 $MAKELOG
       fi
@@ -65,7 +64,7 @@ if test -e $SUMO_BINDIR/sumo -a $SUMO_BINDIR/sumo -nt $PREFIX/sumo/configure; th
   # run tests
   export PATH=$PREFIX/texttest/bin:$PATH
   export TEXTTEST_TMP=$PREFIX/texttesttmp
-  find $SUMO_BATCH_RESULT -mtime +20 -type f | xargs -r rm
+#  find $SUMO_BATCH_RESULT -mtime +20 -type f | xargs -r rm
   rm -rf $SUMO_REPORT/* $TEXTTEST_TMP/*
   if test $FILEPREFIX == meso; then
     tests/runInternalTests.py "b $FILEPREFIX" &> $TESTLOG
@@ -85,7 +84,7 @@ basename $MAKEALLLOG >> $STATUSLOG
 export CXXFLAGS="-Wall -W -pedantic -Wno-long-long -Wformat -Wformat-security"
 ./configure --prefix=$PREFIX/sumo --with-python \
   --disable-double-precision --disable-subsecond --disable-internal-lanes \
-  --enable-debug --enable-memcheck --enable-messages &> $MAKEALLLOG || (echo "configure with all options failed" | tee -a $STATUSLOG; tail -10 $MAKEALLLOG)
+  --enable-debug --enable-memcheck &> $MAKEALLLOG || (echo "configure with all options failed" | tee -a $STATUSLOG; tail -10 $MAKEALLLOG)
 if make >> $MAKEALLLOG 2>&1; then
   make install >> $MAKEALLLOG 2>&1 || (echo "make install with all options failed" | tee -a $STATUSLOG; tail -10 $MAKEALLLOG)
 else
